project:
  type: website
  output-dir: docs

website:
  title: "Geneseo Tree ID Project"
  navbar:
    pinned: true
    left: 
      - text: Tree Species
      - href: treelisting.html
    tools:
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cerulean
    toc: true
    css: styles.css # Reference to the custom CSS file

editor: source

