project:
  type: website
  output-dir: docs

website:
  title: "Geneseo Tree ID Project"
  navbar:
    pinned: true
    left: 
      - text: "Tree Species"
        href: treelisting.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cerulean
    toc: true
    css: styles.css

editor: source
